### ISSUE TITLE
<axa-link> alignment issues

### ISSUE THREAD

**Issue by cge** [axa-ch/patterns-library#1062]
When a number of `<axa-link>`s are listed vertically, it seems icons and label text do not align properly. The misalignment of the text is what hits us the hardest. Please see an example here:

![axa-link-alignment](https://user-images.githubusercontent.com/1171773/58962125-d3da4d00-87aa-11e9-9010-96605109d94c.png)

**Comment by raphaellueckl** [comment]
@cge I will look into this now.

**Comment by raphaellueckl** [comment]
The icons we have a sadly not normalized. They come in all kinds of sizes, which causes this issue. I will have to make sure that this works again. I am not sure how I should approach this issue, because there are several ways. The best would be that our designers would deliver those icons in standard sizes.

**Comment by cge** [comment]
Hi @raphaellueckl , thanks for looking into this. The [design guidelines](https://brandhub.axa.com/web/49d0c5166233fff7/axa-digital-guidelines-icons/) seem to categorise by size, with functional icons at 16x16 px.

My suggestion would be to have a `opacity="0"` background of the implied size, which could function not only as a surface for centering icon paths, but also as a clickable surface.

Not looked at Material UI icon definitions yet, but they have the familiar round background, making alignment pretty easy.

**Comment by AndyOGo** [comment]
Hey guys @cge @raphaellueckl 

Unfortunately the global design icons aren't made for the Web and even the approved material design icons have small glitches...

Anyway I had all those icon problems at the redesign of axa.ch, so because it is a generic problem I created a dedicated repo for it, with all steps needed to fix them.

I'm sure @LucaMele remembers that situation and may chims in to help.

https://github.com/axa-ch/aem-icons

**Comment by raphaellueckl** [comment]
done

@AndyOGo I will ask him about that, thanks!
