### ISSUE TITLE
old patterns-library version 2.0.1-beta.245 conflicting with datepicker (new patterns-library)

### ISSUE THREAD

**Issue by francescoRovetto** [axa-ch/patterns-library#1141]
It seems that the old patterns-library doesn't get along with the new one. Does that mean, I Need to eliminate the old patterns-library before using the datepicker?

TypeError: wcNode.setProps is not a function
updateWebComponentProps
C:/eplatform/opk-client/node_modules/@axa-ch/patterns-library/lib/js/with-react.js:189

  186 |       wcNode.classList.add(dataProps.className);
  187 |     }
  188 | 
> 189 |     wcNode.setProps(dataProps);
      | ^  190 |   }
  191 | }, {
  192 |   key: 'componentWillUnmount',

componentDidMount
C:/eplatform/opk-client/node_modules/@axa-ch/patterns-library/lib/js/with-react.js:126

  123 | var isDefined = this.state.isDefined;
  124 | 
  125 | if (isDefined) {
> 126 |   this.updateWebComponentProps();
      | ^  127 | } else {
  128 |   // make sure that the custom element is ready
  129 |   // ref: https://developer.mozilla.org/en-US/docs/Web/API/CustomElementRegistry/whenDefined

**Comment by LucaMele** [comment]
@francescoRovetto, yes v1 and v2 are incompatible

**Comment by francescoRovetto** [comment]
Okay- thanks for the quick Response. I still need the old patterns-library for the header, which is not yet available in v2. What do you recommend?

**Comment by LucaMele** [comment]
@francescoRovetto only if you define components from v1 and v2 there is a collision, not if you have them just installed. I suggest the following:

- Remove old patterns library completely including the polyfill
- Add only the header as dependecy like here: https://github.com/axa-ch/patterns-library-examples/blob/develop-v1/react/src/Header.js
- Important that no-where you have this:
- - `import '@axa-ch/patterns-library'` because if so you load the whole thing and then you have that conflict. 

Try the stpes above and let me know

**Comment by AndyOGo** [comment]
May I chim in? 

The best solution would be if the patterns-library itself namespace or versions it's own modules down to the code.
TBHO I have to admit we made that mistake at the very beginning of even V1.
I realized that issue and created #579 in October last year and suggest to reopen it.

I leave it up to you, how you want to handle it.

**Comment by LucaMele** [comment]
@AndyOGo thank you. 

We considered the idea of having something like `<axa-v2-button>` but that would have been ugly. If we wanted the to have full semver we had to invent something like: `<axa-v234-button>`. Only in this way there would have not been any issues. But it is too messy so we decided to keep semver only in the node module dependency, regardless of custom element registry conflict. The truth is, we don't have a big customer based and we prefer to help migrate to v2 instead of keeping v1 alive.

Another option i evaluated is one last release on v1 where we rename all tags with the following names: `<axa-old-button>`. But then decided it wouldn't have improved a lot devs live as they would have had to update and with that comes lots of other issues.

**Comment by LucaMele** [comment]
The collision issue is only because of 1 HTML tag name can have of course 1 handler.

**Comment by LucaMele** [comment]
@AndyOGo the issue you posted is not related to @francescoRovetto issue

**Comment by AndyOGo** [comment]
@LucaMele Thanks for your quick response.

You are right it will become ugly code.
I think it would be only beneficial for code which is evaluated globally like CSS.
In case some use the button from v1 and v2, I think he should rather stick to one implementation.

In general I would appreciated namespacing.

**Comment by francescoRovetto** [comment]
Hi @LucaMele ! I tried the steps, which you recommended but I still get a conflict:

TypeError: wcNode.setProps is not a function
updateWebComponentProps
C:/eplatform/opk-client/node_modules/@axa-ch/patterns-library/lib/js/with-react.js:189

  186 |       wcNode.classList.add(dataProps.className);
  187 |     }
  188 | 
> 189 |     wcNode.setProps(dataProps);
      | ^  190 |   }
  191 | }, {
  192 |   key: 'componentWillUnmount',

**Comment by LucaMele** [comment]
Try without header and see if the same issue appears. Cause the error comes from `@axa-ch/patterns-library/lib/js/with-react.js`

**Comment by LucaMele** [comment]
Dont include any other stuff of v1 apart of header

**Comment by LucaMele** [comment]
button will collide

**Comment by francescoRovetto** [comment]
Aaaah ok

**Comment by francescoRovetto** [comment]
Hi @LucaMele , it almost works. It takes some time to migrate on v2.

Now I get following error:

RangeError: invalid language tag: undefined
getAllLocaleMonthsArray/<
C:/eplatform/opk-client/node_modules/@axa-ch/patterns-library/lib/js/date.js:13

  10 | objDate.setDate(1);
  11 | [].concat(_toConsumableArray(Array(12).keys())).forEach(function (index) {
  12 |   objDate.setMonth(index);
> 13 |   var month = objDate.toLocaleString(locale, {
     | ^  14 |     month: 'long'
  15 |   });
  16 |   month = month[0].toUpperCase() + month.slice(1);

getAllLocaleMonthsArray

I think, it has nothing to do anymore with v1. I removed everything except header.

**Comment by MKaHead** [comment]
Hey guys, I will support @francescoRovetto
