### ISSUE TITLE
Link/styles: ensure fixed line-height instead of inheriting

### ISSUE THREAD

**Issue by MarekLacoAXA** [axa-ch/patterns-library#1158]
In the axa-link component please fix the line-height to the font-size.

Currently the line-height inherits from the outside world, but the font-size does not, so the result isn't ideal:

Design mockup:
![image](https://user-images.githubusercontent.com/43809369/61115736-64cfd280-a493-11e9-912a-1b1e72ee096e.png)

Actual result (body has 1.5 line-height applied):
![image](https://user-images.githubusercontent.com/43809369/61115809-96489e00-a493-11e9-8bd8-6ee4f453d1c3.png)

Thanks!

**Comment by MKaHead** [comment]
Hi @MarekLacoAXA, thank you for creating the issue. The link will get some changes and love, soon!

**Comment by raphaellueckl** [comment]
@MarekLacoAXA According to the styleguide, this is how the link should look: 
https://design.axa.com/web-guidelines/buttons-and-links#types-of-links

So the fix I would implement is, that I would overwrite the line-height, so that it does not get imported. The font-size does not get imported because I am already overriding it, would be my guess.

Would that be ok for you?

Thanks for reporting this!

**Comment by markus-walther** [comment]
This is currently under discussion with our designers. The reference guide has changed to https://www.figma.com/file/6zurYk3bJpzUg0H2THSxGF/AXA-UI-Kit?node-id=226%3A952.

Note that the original line-height inheritance no longer applies anyhow (version 2.0.7).

Rather, the current discussion is on the exact line-height value to be imposed, and on alignment details for icons.

After the discussion is settled, work will resume on this ticket.

**Comment by raphaellueckl** [comment]
I cannot reproduce this with the current version. IMHO this is fixed, line-height does not get inherited in my testings.

Please re-open, if this is still an issue.
