### ISSUE TITLE
package-lock.json of our components are outdated

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1282]
`npm i` and `lerna build` do NOT update the package-lock of the components.

```
"name": "@axa-ch/button",
  "version": "2.0.3",
```

package-lock:
```
"name": "@axa-ch/button",
	"version": "1.1.11",
```

**Comment by raphaellueckl** [comment]
https://github.com/lerna/lerna/issues/1883

They actually do update it, but it seems that only happens when a dependency change to package.json happens.

I will open an issue on their repo and close this one here.

**Comment by raphaellueckl** [comment]
I just found out that removing the --hoist flag actually updates all package locks. Since hoist means, the dependency is moved to the root module, it might just be overhead to refresh the package-lock json. An npm install in that local folder will still update the dependencies, and that's the only thing important, because an uninstalled package cannot be run anyways.
