### ISSUE TITLE
AXA Input text changes height when displaying error message 

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1334]
Behavior: 
AXA input text changes height it occupies when displaying error messages.

![Screen Shot 2019-09-16 at 10 29 00 AM](https://user-images.githubusercontent.com/8245106/64943797-f9c4c280-d86c-11e9-9c63-1cf46afff031.png)
![Screen Shot 2019-09-16 at 10 29 15 AM](https://user-images.githubusercontent.com/8245106/64943803-fc271c80-d86c-11e9-97ba-96d6748392a1.png)

Expected behavior:
Showing error message on input does not change layout of the form.

**Comment by TommyHoliday** [comment]
hey aleksandar, 
thanks for your ticket. the pattern lib- and design team discussed that quite intensively as well. it's an intended decision that we don't reserve space for error messages due to fact that the messages can be quite long (multiline).

**Comment by kenaxa** [comment]
@salle18 This behavior is on purpose. Reason why we changed it from reserved space was following: 

- You could reserve max. 1 line otherwise the space in between would be too big
- More than 1 Line of text is reached easily on mobile devices
- If more than 1 Line it would jump anyways
- It was apparently bad practices from a coding perspective as stated by Andy (@AndyOGo )

We also took a look at major platforms that are depending on forms such as like Google and they behave the same as we decided. 

Feel free to ask question if context is needed on the slackchannel #ux-ui-support to reach out to us.

Cheers, 
Ken
