### ISSUE TITLE
Run UI tests with Browserstack

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1355]
Testcafe can connect to Browserstack. Its not active because there are problems wie IE. So fix that to use that nice feature.

**Comment by raphaellueckl** [comment]
That would be a ton of fixes we would have to deliver just for this feature. At max I would do a smoke test and see if storybook gets rendered in IE here an there. But since I think there is a deadline forming for IE support somewhere on the horizon, I would ignore this issue until.... it fixes itself. 👀

**Comment by danyball** [comment]
Yes, but what about Firefox, Safari, MobileDevices,... ? To run the UI tests here would be a good think. We could start with a browserstack run that do not stop the build.

**Comment by danyball** [comment]
Closed because we migrate to another test framework.
