### ISSUE TITLE
AXA Input Text - forward React reference to the underlaying input

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1359]
It would be useful if we are able to get reference of the underlaying input -> think focus for instance ( related #1358 ) and in some cases 3rd party libraries are trying to get reference of the input.

Furthermore reference can not be set on functional components at all so we are not able to get reference on axa input text at all.

**Comment by markus-walther** [comment]
[Point 12, React Refs](https://github.com/axa-ch/patterns-library/blob/develop/ARCHITECTURE.md) in the ARCHITECTURE document seems to address at least the second part of this issue - would doing this yourself satisfy the feature request?

**Comment by markus-walther** [comment]
In general, getting a reference to some node in the inner structure of a component is discouraged, because components are opaque and reserve the right to inner-structure changes. 

Technically, this would be possible here, but already more difficult in components that use ShadowDOM.

All interaction should be via the documented API (in the component's README), no assumptions should be made on the inner structure of a component.

**Comment by salle18** [comment]
> [Point 12, React Refs](https://github.com/axa-ch/patterns-library/blob/develop/ARCHITECTURE.md) in the ARCHITECTURE document seems to address at least the second part of this issue - would doing this yourself satisfy the feature request?

Not sure how to do this, example using AXAInputText with forwardRef would be really helpful.

**Comment by markus-walther** [comment]
We will not support referencing internal DOM nodes of a component, because - as stated above - this is architecturally unsound.
