### ISSUE TITLE
Feature Branch Deployment: post relevant URL to Slack

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1389]
Would be cool if the URL has some more infos to open the relevant component with 1 click.

Is:
`https://axa-ch.github.io/plib-feature/feature/dropdown-autocomplete`

Should be:
`https://axa-ch.github.io/plib-feature/feature/dropdown-autocomplete/?path=/story/molecules-dropdown--dropdown`

An idea could be to scan the branch for changed `story.js` and picked the first to occur. @raphaellueckl ?

**Comment by raphaellueckl** [comment]
This would be extremely hard to do with my bash script. Also, often you don't just work on one story. This feature branch deployment is also mainly for reviewers, either from PR or our designers. They don't care about the latest commit, they want to see the whole change at once I guess. It would be kind of impossible to accurately predict which story would be most suitable to show upon click.

**Comment by danyball** [comment]
We are often work on multiple components on one PR? I dont think so. Sometime ok, but not realy often. In most times there is just one story.js which is changed. And if there are more than 1 story.js changed, DonaldDuck just post the url as it is now.

Can i have a look at the bash script? Would try something.

**Comment by raphaellueckl** [comment]
You can, but I can tell you right away that what you are trying is almost impossible and will need a lot of effort. I don't see this as a big problem, since we don't use the feature branch deployment that often.

What you need to do:
- Checkout the project (takes time, slows down our build process)
- Find the most recent git commit
- Check the changes within there
- If 5 files changed and 3 are more or less in the same path, map this path to a storybook link (this might be only possible manually, which would mean we would need to register every component we have also in the bash script, which I'm highly against).
- Write an algorithm that checks if it needs a specific link or if it should use the standard link. That decision might be wrong (maybe you checked in 5 files but only one change is currently what you want to share with somebody), it's not really possible to make this work 100% imho.

**Comment by raphaellueckl** [comment]
What I would like way more would be a feature that adds the link to the pullrequest, similar to what azure and travis is doing: 

<img width="699" alt="Screenshot 2019-11-11 at 08 23 55" src="https://user-images.githubusercontent.com/8248662/68568705-a5992180-045c-11ea-9c5e-aaa7f9b7cf0a.png">

**Comment by danyball** [comment]
I dont need a link to the PR, but why not. 

Can you show us the Feature branch script?

**Comment by raphaellueckl** [comment]
I wasn't aware that this issue is still open, but we already discussed this with a consensus, so I close it here.

Feel free to reopen if any approach would emerge, but I don't see this being a good possibility.
