### ISSUE TITLE
Lockdown plib polyfill depdency

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1452]
https://github.com/axa-ch/jest-test-plib-v2/pull/2

Andreas Deuschlinger:house_with_garden:  2 minutes ago
I found the culprit, a new version 2.3.0 of @webcomponents/webcomponentsjs got released at Sep 19. Since then Jest is broken :man-facepalming:
I made another  PR with it being locked down to 2.2.10 and it works :tada:
https://github.com/axa-ch/jest-test-plib-v2/pull/2

**Comment by AndyOGo** [comment]
Since `2.3.0` Jest throws **TypeError: The custom element constructor's prototype is not an object.**:

From my insights it seems that two **different** `Object` constructors are being used, which causes this check to fail.
https://github.com/webcomponents/polyfills/blob/75717f84bbb6ba165dacbf6c406da5845bcb9664/packages/custom-elements/src/CustomElementRegistry.js#L168-L173

Reproduction Repo with relevant analysis in PR description:
https://github.com/axa-ch/jest-test-plib-v2/pull/1

Lock down to `2.2.10` to mitigate this type error:
https://github.com/axa-ch/jest-test-plib-v2/pull/2
