### ISSUE TITLE
Multiline button-text loses a lot of padding

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1667]
I just got a mail mentioning asking if we could increase our button sizes. I noticed then, that we have dedicated sizes, but they somehow behave a bit weird, when it comes to multiline text.

This is a button with `size=large`:
<img width="304" alt="Screenshot 2020-02-21 at 08 53 00" src="https://user-images.githubusercontent.com/8248662/75015347-b0fede80-5488-11ea-8a37-9b34a7ccbfa4.png">

This is a button with `size=large` but wrapping text:
<img width="1215" alt="Screenshot 2020-02-21 at 08 53 25" src="https://user-images.githubusercontent.com/8248662/75015382-bfe59100-5488-11ea-9475-44512610d911.png">

I guess we should also have the padding on multiline text. Has to be clarified with a designer.

**Comment by LucaMele** [comment]
I would ask the designer if is an issue or is meant to be. As far as i remember was on purpose to reduce padding if it gets to 2 lines so that text still fits in the same button height.

**Comment by LucaMele** [comment]
I guess we can call it common best practices

Just a quick search on google images shows you that almost every button since windows XP behave like this: https://www.google.com/search?q=buttons+multiline&sxsrf=ALeKk03TBgqgbUn17Lr_p_kWZCEpNlV2ug:1582272626160&source=lnms&tbm=isch&sa=X&ved=2ahUKEwiXucfumOLnAhXJwqYKHSR5AMwQ_AUoAXoECAwQAw&biw=1440&bih=749

**Comment by LucaMele** [comment]
wont fix
