### ISSUE TITLE
Cursor jumping to the end in Input Text (only reproducable in Safari)

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#1691]
Hi together,

we discovered a bug in the Input Text Component in Safari Browser (Mobile and Desktop). Here are the steps, to reproduce it in the axa patterns library storybook.

1. open this link https://patterns.axa.ch/?path=/story/components-atoms-input-text-react-demos--feature-input-text-controlled-uncontrolled
2. in **"Controlled"** input text, type "test12345"
3. now set the cursor somewhere in between that string
4. type something  --> the cursor is jumping to the end of the input text

![image](https://user-images.githubusercontent.com/57704956/76772724-ab539a80-67a1-11ea-9eb9-35c1dad64604.png)

This Bug is urgent as we are using this component for our Forms and the user is not able to correct his input, and we will have Go Live at 6.April.

thanks and best regards,

Quan

**Comment by markus-walther** [comment]
Its a known 'feature' of programmatic updating of inputs, cf. https://www.mutuallyhuman.com/blog/the-curious-case-of-cursor-jumping/, which also notes it's particularly bad for Safari and goes on to suggest mitigation strategies.

In your case, could you avoid running the component in _controlled_ mode under React? What exactly forces you interfere with the user's typing? Could you implement some of the suggestions of the linked article?

**Comment by chiquan-hong** [comment]
Hi Markus,
thanks for your suggestions. I checked that suggetions and also checked if its possible for us to use "uncontrolled" mode. But the problem is, we need to do real-time validations in our input fields, therefore we need to use the "controlled" mode. And as far as i know, that is not possible with "uncontrolled" components.

**Comment by chiquan-hong** [comment]
Me and another Developer, we tried different solutions. We also deleted the onChange Method, so that there is no rerendering but still the cursor is jumping to end. 
I think your help is needed now, as we dont know what to do more now.

**Comment by markus-walther** [comment]
I am glad to help.

One of the strengths of the Patterns Library is that it is open-source. Users are explicitly invited to also consult the source, in particular for finer points of the implementation that may be under-documented.

In this case, https://github.com/axa-ch/patterns-library/blame/develop/src/components/10-atoms/input-text/index.js#L280-L283 provides a clear clue.

The responsible commit in turn leads to a pull request, whose description is also helpful: https://github.com/axa-ch/patterns-library/pull/1493

Now, it is strictly untrue that for real-time _validation_ under React you somehow _need_ to be in controlled mode. Validation is a read-only operation that does not need to programmatically write new input-field values (which would be bad UX anyway under most scenarios, see the link in my first comment above).

You can just register an `onChange` handler and will get called back character-by-character, and do your validation there.

Crucially you should avoid ever setting the `value` property, since Safari is broken in this regard, i.e. operate in uncontrolled mode if you need to support Safari.

**Comment by markus-walther** [comment]
To add to my previous comment: We have studied https://reactjs.org/docs/uncontrolled-components.html carefully, and this inspired the `defaultValue` property that is also available for `<axa-input-text>` (see the README).

Setting `defaultValue` allows you to preset an input-field initially without causing controlled mode.

**Comment by raphaellueckl** [comment]
Hi all

We decided with Martin Stüdle, that we will not deliver a near term fix here. However, we would support you hands-on, if we can (with the 'uncontrolled' idea).

Reason: This bug needs to be resolved by safari and we cannot workaround it without making a huge effort, that will lead to other side effects.

**Comment by chiquan-hong** [comment]
Hi all,

i implemented a workaround which works for us now. 
Actually, i implemented that workaround at the beginning already but there was one thing i didnt know.....when i deployed to ACC, i had to delete the browser cache of my safari browser on my iPhone (everytime), otherwise the sources are not updated. That is strange, because at Desktop Browsers, that is not necessary.
After i found that out, i implemented my first workaround (that was, remember the  cursor position and set it manually) and now it seems to work for safari.

Anyway, thank you guys very much for helping me and for your time.
I will close this issue now.
