### ISSUE TITLE
Checkbox React Example not working

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#1707]
https://patterns.axa.ch/?path=/story/components-atoms-checkbox-react--checkbox-uncontrolled

You cant unselect checkbox in this example. If you deselect "checked" knobs it works.

**Comment by danyball** [comment]
Possible the same like #1706 ?!

**Comment by markus-walther** [comment]
This is just controlled-mode at work! The knob for 'checked' should not have been applied here, setting checked activates controlled-mode for a checkbox.

If you looked very closely, you could see that, because for a few milliseconds the checkbox state flipped visually, only to be dragged back by controlled mode.

**Comment by markus-walther** [comment]
Since the storybook label says this is an example of checkbox under React in _uncontrolled_  mode, the solution is to remove `checked` from the knobs.
