### ISSUE TITLE
Testing with enzyme

### ISSUE THREAD

**Issue by raphaellueckl** [axa-ch/patterns-library#1749]
Feedback from @MKaHead

A "package to import" would be helpful, so that testing with enzyme works better.

Apparently, @MarekLacoAXA seems to have the most experience with enzyme so far, AFAIK. Probably contact him for ideas.

**Comment by danyball** [comment]
Develop solutions for a specific test framework sounds not very good. So what is the problem here?

**Comment by MKaHead** [comment]
For example if you build a Header cp and inside you using a plib cp and then try to test/render it with enzyme the Header cp will break, because enzyme render in node env there is no browser. So for now our fixes was importing webcomponents polyfill and a mutation observer implementation and I think even more webpack related stuff, see [here](https://github.com/axa-ch/patterns-library-examples/commit/870f94420239e9c99cd25a6050e078375d64a815) Would be easier if we would have a plug and play module like the polyfill one, for example something like pattern-library/testing-kit   and there are all the necessary imports.

Should minimal work work for axa pods and cra 3+.

**Comment by danyball** [comment]
Ok, a customer needs some work to get his testing-framework webcomponents ready. But i am not sure if that should be part of the PL. Could be, if other frameworks needs these helper too. I am against a development of an enzyme only solution (enzyme could be outdated tomorrow).

In my opinion that should be a extra git project. Supportet by all the enzyme-users which are using WC or the PL. The PL-Team could then take on a consultative role. And we can mention that in our docu.

**Comment by MKaHead** [comment]
ah yeah not only a a specific enzyme problem, you get the problem everywhere where you try to render it outside the browser. Yeah maybe it's to much for module, but there could more than this specific fix in the kit, so extendable for more helpers. In the end there should be better documentation to deal with this problem.

**Comment by markus-walther** [comment]
I think the problem is trying to render outside the browser, when not a single end user does that, who is the entity experiencing the problems that a test tries to prevent...

**Comment by markus-walther** [comment]
Fruitful discussion with @MKaHead on this issue. Key points:

- non-browser-based testing has speed advantages (though browser-based e2e testing is getting speedier, e.g. with puppeteer/playwright)
- sometimes business logic is in testing focus, not fidelity of pixels on page
- mixing virtual-DOM-based frameworks like React with strictly DOM-based ones like lit-element (which underlies the AXA pattern library = PL) inevitably ties testing to DOM, at least emulated DOM (e.g. jsdom); then the quality of the emulation becomes an issue
-  improving non-browser-based testing sends a supportive message to the PL user community

**Comment by raphaellueckl** [comment]
@markus-walther can we close this issue? We discussed that part once at a daily and decided, that we should enable our users to do browser-based testing.

**Comment by raphaellueckl** [comment]
Just noticed that this is my issue. I will close it here. Markus was the main driver of this discussion anyways and we agreed on the points.
