### ISSUE TITLE
Checkbox controlled-mode not working if initial checked property is false

### ISSUE THREAD

**Issue by salle18** [axa-ch/patterns-library#1761]
Version: "@axa-ch/checkbox": "^4.0.1"

When initial checked property is false checkbox does not enter controlled-mode.

Reproduction link:
https://codesandbox.io/s/practical-leaf-lc0gs

**Comment by markus-walther** [comment]
Bug could be reproduced and is accepted. Exemplary bug-reporting!

**Comment by markus-walther** [comment]
Reason for the bug is deep in the guts of the PL system: by virtue of being of type Boolean, the 'checked' property is treated as an _attribute_ in the React wrapper logic, and by being falsy, the attribute 'checked' gets removed (by val(...)). Apparently that does not trigger the setter for 'checked', which is where controlledness is determined.
