### ISSUE TITLE
Autofocus functionality for input fields

### ISSUE THREAD

**Issue by TommyHoliday** [axa-ch/patterns-library#1798]
There are scenarios where we only have one single input field on a screen. (e.g. sales funnel) It would be great to have to possibility to add autofocus for such fields to improve the UX.

**Comment by danyball** [comment]
Internal hint: `dropdown` do have this functionality.

**Comment by markus-walther** [comment]
@TommyHoliday https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Input#attr-autofocus says:

"No more than one element in the document may have the autofocus attribute. ...

For better usability, avoid using `autofocus`."

Also, it's a bit dangerous to put it in all the input components, because the page-level constraint  ('no more than one...') is hard to enforce if autofocus is component-level.

Not denying the above scenarios, but what would you say to those concerns?

**Comment by TommyHoliday** [comment]
@markus-walther thanks for your input! i'm totally aware of those concerns. but this should be in the responsibility of the product team to decide whether it makes sense to implement the autofocus or not. as described above, i would definitely only recommend to use it if there is only one single form element on the screen – e.g. like the google home page.
