### ISSUE TITLE
Datepicker: Enable on key event handlers that passes keycode

### ISSUE THREAD

**Issue by campsafari** [axa-ch/patterns-library#1807]
Currently it is not possible to get access to the internal input field via ref in react which makes it impossible to hook into i.e. keyboard events to do auto formatting for the input value.

**Comment by danyball** [comment]
Please do not change internal elements. We just support use cases we have documented. So, my question here is: What do you want to do? Or why do you want to do that?

**Comment by campsafari** [comment]
We don't want to change internal elements, we merely need key event handlers for enter key, etc.
We have a feature request that the date should be auto formatted when the enter key is pressed.
So that 123 + enter becomes 12.3.2020

**Comment by LucaMele** [comment]
@campsafari The internal structure is per design a black box. Reason why: The interface between a Component and its customer is and always will only be the attributes and events on the root element. This is essential for stability. We can change the internal structure in the HTML and release the component having a minor version because the interface is the root element. If you access internal structure, you will have problems in updating.

We provide a lot of event handlers, not all of them, but only those comliant with the UX of the component. We aim to unify the Look & Feel of AXA. This includes also which events are or are not exposed. As an example, If you validate on input and someone else on change, on the website the customer will still have 2 different way of using the same element. 

Nevertheless, please let us know what event handlers do you need exactly on the root tag that are not there yet

**Comment by LucaMele** [comment]
If the feature you requested makes sense for all of AXA Switzerland and is approved from the UX Team, we will implement it. Just understand that the datepicker is used in multiple pages on axa.ch and in different applications. Imagine how confusing for the user if ONLY your DatePicker behaves like that but looks the same as everywhere else. Therefore, if we decide to have that feature, we need to give it to everyone

**Comment by campsafari** [comment]
according to the feature request from claims we would only need the enter key event.

**Comment by TommyHoliday** [comment]
as discussed with @campsafari and @LucaMele we'll implement this feature. reason: the new claims forms will be used by end-users as well as internal employees (power users) who will need to enter quite a lot of dates on a daily basis. this will greatly improve their productivity. 🚀

we'll only implement the enter-event, everything else will not be handled by the datepicker component.

**Comment by LucaMele** [comment]
Thanks @TommyHoliday

**Comment by LucaMele** [comment]
Beacuse also the feature `123 + enter becomes 12.3.2020` is something a normal user wont know about, the risk of confusion across datepickers on axa.ch, for our B2C users, is minimal

**Comment by danyball** [comment]
@campsafari Why dont you use just that vanilla JS code for your usecase?

```
document.querySelector('axa-datepicker').addEventListener('keydown',(e)=>{
console.log(e.key, document.querySelector('axa-datepicker').value); 

if(document.querySelector('axa-datepicker').value === "123") 
   document.querySelector('axa-datepicker').value = "12.03.2020";

})
```
