### ISSUE TITLE
We should visualise in Storybook the breakpoints

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1811]
Thomas Veit  10:06 AM
wie sind unsere breakpoints auf axa.ch?

Luca Mele:speech_balloon:  10:07 AM
https://github.com/axa-ch/patterns-library/blob/develop/src/components/00-materials/styles/30-layout.scss

GitHubGitHub
axa-ch/patterns-library
AXA CH UI components library. Please share, comment, create issues and work with us! - axa-ch/patterns-library
10:07
// Breakpoints
$breakpoint-small: 576px;
$breakpoint-medium: 768px;
$breakpoint-large: 992px;
$breakpoint-xlarge: 1200px;
$breakpoint-xxlarge: 1440px;

Thomas Veit  10:07 AM
aaaah perfekt! ich habs auf patterns.axa.ch nicht gefunden :slightly_smiling_face:
10:07
danke dir!!

Luca Mele:speech_balloon:  10:07 AM
ok NP
10:07
ist ein issue wenn man es nicht findet auf patterns.axa.ch :slightly_smiling_face:
10:07
soll ich ein ticket machen?

Thomas Veit  10:08 AM
ich persönlich fänds sehr cool ja! aber vielleicht suchen devs eher auf github… ich weiss nicht :smile:

**Comment by flexbox** [comment]
Hey @LucaMele I think you can add this story to the issue

As a developer
I can have an overview of the responsive behavior
So that check if the layout is not broken

- [ ] Add the playroom addon https://github.com/rbardini/storybook-addon-playroom

![image](https://user-images.githubusercontent.com/360936/84672326-b648d300-af28-11ea-8879-9d7d1536bab6.png)

**Comment by 01231** [comment]
"generate Playroom snippets from stories (experimental)" 😕

**Comment by danyball** [comment]
Try to use https://storybook.js.org/docs/react/essentials/viewport
