### ISSUE TITLE
Demo for top content bar is broken. Text padding is not correct and button not displayed (add CTAtext in knobs)

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#1861]
https://patterns.axa.ch/iframe.html?id=components-molecules-top-content-bar--top-content-bar&knob-ctatext=test&knob-variant=&knob-href=&knob-Text=Undefined%20flighting%20object%20detected%20in%20your%20region.%20People%20are%20paniking.%20Stay%20calm&knob-Add%20axa-link=

![Screenshot 2020-07-08 at 14 11 04](https://user-images.githubusercontent.com/275235/86917255-0e888480-c125-11ea-9525-a789cf448c24.png)

**Comment by danyball** [comment]
The DOM Node is wrongly replaced by `component versioning` - see here:

![image](https://user-images.githubusercontent.com/7448004/88145322-8dd48880-cbfa-11ea-8957-27b96f772e3c.png)

@markus-walther

**Comment by markus-walther** [comment]
No, the versioned button-link is entirely correct. Inherent dependencies of a component should be rewritten by versioning, this is by design and correctly modelled in the top-content-bar implementation.

What's wrong is rather that the top-content-bar CSS references unversioned  custom-component tags in its selectors. This is an anti-pattern now, all such references should be to appropriate classes instead.
