### ISSUE TITLE
Wrong content and text on the page "colors"

### ISSUE THREAD

**Issue by johannabuguet** [axa-ch/patterns-library#1888]
<img width="852" alt="Capture d’écran 2020-07-20 à 16 26 14" src="https://user-images.githubusercontent.com/68434693/87949011-be56de00-caa5-11ea-87ad-53fb8f88727b.png">

The last part of the page "[colors](https://axa-design-system.netlify.app/colors)" is about typography but it should be about colors

Expected Behavior:  

- The text has to be changed  (@flexbox Ronan have the design ready) 

- the button should lead to this page : https://design.axa.com/web-guidelines/color

Current Behavior:
- wrong text 

- wrong link

**Comment by danyball** [comment]
@johannabuguet I think you are on the wrong repo for this issue?! Our project is https://patterns.axa.ch/

**Comment by flexbox** [comment]
@johannabuguet 
If you check on the top left

This is the home for axa-ch
![image](https://user-images.githubusercontent.com/360936/88033501-bf3c4e00-cb3f-11ea-8989-a6222b1c180d.png)

I "forked" the repo to share the codebase 
![CleanShot 2020-07-21 at 10 49 38](https://user-images.githubusercontent.com/360936/88033739-01658f80-cb40-11ea-9e40-7e60b41fb3bd.png)

and your issues are living there 😉 
https://github.com/team-haigo/patterns-library/issues

![image](https://user-images.githubusercontent.com/360936/88033840-24903f00-cb40-11ea-989a-3d734039d20b.png)


Can you close this issue because it's duplicated with https://github.com/team-haigo/patterns-library/issues/83

**Comment by johannabuguet** [comment]
Oopsie sorry, It was my first day on github haha. 
I'll copy my feedback in the proper place. Sorry for the trouble
