### ISSUE TITLE
don't commit dist folder to git repo

### ISSUE THREAD

**Issue by zuzana** [axa-ch/patterns-library#196]
### Suggestion: Let's not commit dist folder to git repo. 

Why?

1. It will be easier for developers to see what files they have actually changed when running `git status` 
1. Diffs will be smaller and developers will have easier understanding of current changes or changes in previous commitss running `git diff`
1. Pull requests will include only relevant files that should be reviewed (no minified files or things that weren't worked on)

@axa-ch/patterns-library is published to npm that stores built code so there's no need to store it in GitHub as well.

**Comment by AndyOGo** [comment]
@zuzana 
Please read the docs, for local development we provide `npm run serve`. Which won't change anything within `dist/` and `docs/`.

We decided to go this direction to avoid stack incompatibilities at the consumers end. There goal here is to provide plain HTML, CSS and JS. No transpilation process enforced, but provided as opt-in.

**Comment by LucaMele** [comment]
Hello @zuzana, thank you very much for this suggestion.

We have, as andy said, the npm run serve process which creates a .tmp folder which is in the githignore. The purpose of the dist folder is that people can just download it and use the finished components (after fixing the font issue of course 😄 ). 

I agree, normally dist folders should not be checkied in and in our case is duplicated due to docs. But i think is better for the moment to keep them both. docs is just for github pages and dist for resuable components (at the moment yes they are the same but could change in future).

I really appreciate your suggestion and any improvement suggestion is always super welcome. Thank you.
