### ISSUE TITLE
Datepicker with Input on iPhone, -1 Day is selected

### ISSUE THREAD

**Issue by pavol-marko** [axa-ch/patterns-library#1997]
For more info please contact Esales team: **Nicole Seitz-Reiter** or **Pavol Marko**

On iPhone - safari (all versions), sometimes it comes -1 Day when date in Datepicker is selected with Picker or written manually in input field.
Note: We use V10(in Prod V9) as v12 of Datepicker is currently problematic due to Issue with styles on ACC and PROD.

I Assume that this error is relevant also for V12 however i cannot easy test it due to restrictions (iPhone, v12 is currently Problematic)

## Expected Behavior
Selected date is on Iphone allways correct.

## Current Behavior
Note: The Pattern for this behavior is not easy to Reproduce.
This happens only for certain dates (or date Ranges) - Till now all dates above 2000 seem to be correct. 
Dates examples where it may happen
10.10.1980, 13.2.1970, 13.2.1972 etc..
Besides that this error does not happen allways, e.g. when we were testing V10, we could not reproduce the error from 16:00 - 11:00 - with great amount of tests. Making false positive test for V10, however 11:30 the error could be reproduced again. 
On the Next day the error could be again reproduced at 11:30 .

For more info please contact Nicole Seitz-Reiter (Esales team) or Pavol Marko

## Steps to Reproduce PRE-PROD (ist aber auch im PROD)
1. Use iPhone at 11:30 local time. 
2. Pre-Prod: https://www.acc.axa.ch/de/rechner/rechtsschutzversicherung.html
3. Enter 1 adult,
4. Enter 1 child,
5. Click Online Abschliessen
6. Enter geburtstag: 10.10.1980 (wenn es geht dann andere Datums, zwischen 1960 - 1990)
7. Scroll down - there is this Date as output
![image](https://user-images.githubusercontent.com/55141857/95326025-40cf8c80-08a2-11eb-97ea-ac36bd7eeaf8.png)
![image](https://user-images.githubusercontent.com/55141857/95326058-4c22b800-08a2-11eb-934c-fdceea40ee2b.png)

## Steps to Reproduce Github Pages of UI-Components
IPhone:
1. https://axa-ch.github.io/esales-ui-components/?path=/story/common-axa-datepicker-pure--default-with-validations
2. Enter 10.10.1980
3. Date 9.10.1980 is in output

## Context (Environment)
In Production user has reported error that Birthdate had -1day compared to what was entered.

**Comment by raphaellueckl** [comment]
@markus-walther Would be great if you could have a look. We need to make sure that this really is our issue and not some kind of issue on their side or their wrapper. Moreover, this bug could already be fixed. Eslaes needs to rely on this version, because the pod-aem-patterns-library ships with an outdated (non-versioned) one and they collide in terms of styling. If we cannot reproduce this issue in the Plib, or you know that this is already fixed, we will have to wait for the pod-update.

**Comment by markus-walther** [comment]
We can't work on this until we get a minimal self-contained reproduction with public **source code**. None of the links given above satisfy this criterion.

I note that the Github Pages link wraps the axa-datepicker in a React app, and we don't get to see what the latter is doing, in particular whether there is any form of manipulation of Date objects outside of the axa-datepicker.

Generally, (mobile) Safari is known to be buggy with respect to Date objects.

**Comment by pavol-marko** [comment]
Hi @markus-walther 
In order to be able to reproduce it in Patterns Library Storybook - we need to see output what comes out of your datepicker in 
onDateChange.
Analog to our demo: 
https://axa-ch.github.io/esales-ui-components/?path=/story/common-axa-datepicker-pure--default-with-validations

Problem is not visible in Datepicker self, yet the Date Object comming out in onDateChange has -1 Hour (or has incorrect TimeZone informations) on IPhone in some times for some concrete date ranges.
(This demo was created for purposes of recreating this bug as has no custom logic besides removing timezone from date. Please see the Readme above - it contains the code)

Regard 
  Pavol

**Comment by markus-walther** [comment]
@pavol-marko Which Readme? Certainly the Readme tab for the storybook link you gave contains no code.

 We need to see all code, period. Argumentations why your custom logic may or may not be relevant is no substitute, as we need to be able to clearly separate app from component behaviour.

Please attach or link to said code, as per my comment above.

**Comment by pavol-marko** [comment]
`
const [value, setValue] = React.useState<Date>(null);

  const onDateSelected = (date: Date) => {
    setValue(date);
  };

  const onBlur = (e: any) => {
    action('onBlur', e.target.value);
  };

  const formattedDate = value
    ? dateFns.format(
        //Selected Date is with set Timezone, without removing the offset, date converted to sting may be -1/+1 Day
        //NOTE All other tries failed
        new Date(value.getTime() - value.getTimezoneOffset() * 1000 * 60),
        DATE_FORMAT
      )
    : '';

  return (
    <div>
      <AXADatepickerReact
        defaultValue={''}
        inputfield={true}
        onDateChange={onDateSelected}
        onBlur={onBlur}
        allowedyears={['1900-2020']}
        invaliddatetext={'Min date 01.01.1900, Max date 31.12.2020'}
      />
      <h2>
        Selected date is {value + ''}, ISO formatted: {formattedDate}
      </h2>
    </div>
  );
`

**Comment by markus-walther** [comment]
Based on the above snippet, I strongly suspect that the `formattedDate` function from the application logic is not cross-browser correct. Reason: Desktop Safari (known to be similarly buggy to mobile Safari) returns a getTimezoneOffset of -120, Chrome of -60, for the test date of 10.10.1980! Likewise, for the same date Safari getTime and Chrome getTime differ by 3600000. The computed new date is different as well. (BTW, a mix of date-fns-library functions and native date manipulation is not recommended, since the latter can be buggy...).

However, the axa-datepicker already has a properly formatted string-valued property `outputdate` that is guaranteed to reflect the Date object passed to the `onDateChange` callback! Just get a ref on the DOM node of the datepicker somehow, and read that property in the callback. This `outputdate` appears to be the same for Safari and Chrome, because it uses 'safe' native date functions which are also used in the cross-browser date-fns library.

Unless proven otherwise, I therefore assume there is no bug in the axa-datepicker component itself.

**Comment by 01231** [comment]
Please reopen if you can provide more information.
