### ISSUE TITLE
Datepicker mobile dropdown, wrong language description (choose year, choose month)

### ISSUE THREAD

**Issue by chiquan-hong** [axa-ch/patterns-library#2004]
Hello,

on mobile we figured out, that the dropdown description of the datepicker is not correct.
The Browser-Language is DE but the description in the dropdown of the datepicker is shown in EN.

![image](https://user-images.githubusercontent.com/57704956/95576138-34793a00-0a30-11eb-93a4-492f600c9e9f.png)
![image](https://user-images.githubusercontent.com/57704956/95576166-3e9b3880-0a30-11eb-90e3-d66dca90a837.png)

It should show the description in the language of the browser.

Thanks and best regards,

Quan

**Comment by markus-walther** [comment]
From the README.md:  

- `monthtitle` is the text shown on the month dropdown when nothing is preselected (default: `Choose Month`).

That is, it is up to the application to replace the `monthtitle` property with an adequate string, since the datepicker cannot know what is the best text for all possible circumstances.

I politely suggest to adapt the application s.t. the browser language `navigator.language` drives the choice of an appropriate `monthtitle`.
