### ISSUE TITLE
Better title for our storybook showcase

### ISSUE THREAD

**Issue by danyball** [axa-ch/patterns-library#2071]
If you load the page the title starts with "storybook" and then turns into
![image](https://user-images.githubusercontent.com/7448004/101872974-73d61b00-3b86-11eb-9081-6e8cea0cb41a.png)

We should set a title which describes what that webpage is about.

**Comment by raphaellueckl** [comment]
This is probably not possible without hacks. I am all for that, but this should be an "easy thing" and not some hack that needs to be applied everywhere imho.

The reason it starts with "Storybook" and adapts later is, because the application re-routes the user from "https://patterns.axa.ch" to "https://patterns.axa.ch/?path=/story/welcome--what-is-new".

Every story will adapt the page title therefore.

The main reason I think this is important: Google "axa pattern library" and see how the result looks. Pretty "unoptimized".
