### ISSUE TITLE
use umd format

### ISSUE THREAD

**Issue by zuzana** [axa-ch/patterns-library#219]
I would like to be able to extend class from patterns-library. 
Rollup configuration is using `iife` format. 
Was there a particular reason to switch back to `iife`?
If not, let's use `umd` that should not affect current functionality and enable us to extend exported classes. 
PR #220

**Comment by LucaMele** [comment]
The main scope of the dist bundle is that it just works if the js is included. If we merge this, components wont work anymore if just the javascript is included. If we activate umd, we must as well have a js that loads requireJs or similar.

I would not reccomend to update to umd.

We should rather have es modules exported as well so that in the dist folder we have index.js for just iife and index.es.js for example for es module export.

What do u think about it?

The code snipped on the readme that shows an usage example should still work after this merge.

https://github.com/rollup/rollup/wiki/ES6-modules

**Comment by zuzana** [comment]
I'm fine with whatever enables me to extend class. 
I need to re-render items on AXADropdown component after they have been changed so that's why I tried to solve it with extend.

**Comment by LucaMele** [comment]
Ok so maybe for now we just go with extending from src folder and when the es modules are done we can extend from there

**Comment by LucaMele** [comment]
And please let me know who the re-rendering did work for u :)

**Comment by LucaMele** [comment]
ref: 44
