### ISSUE TITLE
axa-file-upload: allow uploading .msg files

### ISSUE THREAD

**Issue by BeatHeierli** [axa-ch/patterns-library#2278]
We have the [file-upload](https://github.com/axa-ch-webhub-cloud/pattern-library/tree/develop/src/components/20-molecules/file-upload) component in use and want to enable external users/customers to upload emails (.msg)  to us, for example. But no matter whether I leave "allowedFileTypes" empty or enter "application/vnd.ms-outlook", for example, it does not work. Can the component be extended accordingly?

PS: Files with the formats tif or tiff cannot be uploaded either. And why is a png file displayed as a jpg after uploading?

Thx

**Comment by markus-walther** [comment]
@BeatHeierli I have taken the liberty to rewrite your title, preserving your intentions (I hope). Thanks for using our component and submitting your feature request!

The Requirements section of the Readme lists both the restriction to a few well-chosen types and the conversion from PNG to JPG as intentional, stemming from the original stakeholders' and designers/UXers' decisions. However, that was some time ago.

We will discuss the feature request to specify new MIME types and/or file extensions when using axa-file-upload internally - watch this ticket for an Accepted label and more comments if our decision is positive.

**Comment by markus-walther** [comment]
@BeatHeierli This is going to be reviewed by security people, the tightening to a few well-chosen MIME type was deliberate. I will update this ticket once a decision has been obtained.

**Comment by MKaHead** [comment]
Actually upload .msg same problem as in #2328 will be fixed

Only open for discussion would be transformation of png to jpg.
