### ISSUE TITLE
Invalid CSS after '...HwDDchJ3AA==)2\"'

### ISSUE THREAD

**Issue by zuzana** [axa-ch/patterns-library#229]
Hi, 

when using `dist/index.css` I'm getting following error: 

```
Rendering Complete, saving .css file...
{
  "status": 1,
  "file": "./node_modules/@axa-ch/patterns-library/dist/index.css",
  "line": 1,
  "column": 23186,
  "message": "Invalid CSS after '...HwDDchJ3AA==)2\"': expected \"}\", was ') format(\"woff2\"), '",
  "formatted": "Error: Invalid CSS after '...HwDDchJ3AA==)2\"': expected \"}\", was ') format(\"woff2\"), '\n        on line 1 of node_modules/@axa-ch/patterns-library/dist/index.css\n>>  Regular\"),local(\"SourceSansPro-Regular\"),url(data:application/font-woff;chars\n   ------------------------------------------^\n"
}
```

**Comment by AndyOGo** [comment]
@zuzana 
Who is emitting this error? PostCSS?

@LucaMele 
Hmh, it looks like that our change to base64 is causing this issue?

**Comment by zuzana** [comment]
I'm using following setup from [`create-react-app#adding-a-css-preprocessor-sass-less-etc`](https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc):

```
"build-css": "node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/",
"watch-css": "npm run build-css && node-sass-chokidar --include-path ./src --include-path ./node_modules src/ -o src/ --watch --recursive",
```

so that I don't have to use relative paths when importing eg. mixins from node_modules/@axa-ch/patterns/library

That's when the issue is happening, even when I'm not importing dist/index.scss at all. 

Will try to find when it has broken, since previous couple of versions of library were working fine.

**Comment by zuzana** [comment]
It has been broken since version 2.0.1-beta.65, version 2.0.1-beta.64 is working alright.

**Comment by LucaMele** [comment]
Hello, we added all the fonts directly in the index.css file so that it can be included just as `<link rel="stylesheet" href="http://localhost:8080/node_modules/patterns-library/dist/index.css">`

I think it fails for that reason.

Now, if i understand correctly, you are trying to bundle it with a scss preprocessor. I would not reccomend to include it in a preprocessor build as the index.css is not sass syntax and contains the base 64 for the fonts. 

I would suggest to include the needed scss files directly from `src`. Would this work as well? If not, we need to find out why your preprocessor does not recognize base64 and if not, i can make 2 builded css:

1. index.css -> same as 2.0.1-beta.64
2. index.fonts.css -> same as now

Which help would be better for you?

**Comment by zuzana** [comment]
Hi, for now we changed from importing like this:
`@import '@axa-ch/patterns-library/src/styles/mixins/_grid';`
to importing from relative paths 
`@import '../../../node_modules/@axa-ch/patterns-library/src/styles/mixins/_grid';`
in our scss.
It works with create-react-app scripts just fine at the moment.
Closing.
