### ISSUE TITLE
Issues with submenu inside overflow when lots of content is there. It appears randomly

### ISSUE THREAD

**Issue by LucaMele** [axa-ch/patterns-library#312]
![marz-07-2018 11-27-08](https://user-images.githubusercontent.com/275235/37087461-9e5256a8-21fa-11e8-97ea-fec288a7f412.gif)

**Comment by AndyOGo** [comment]
@LucaMele 
Am I right, that it is wrapped within a `<axa-sticky>`?
In that case sticky behaviour for desktop still isn't fully defined - which is why it isn't used at axa.ch.
The quickest option would be to `overflow: scroll` the whole sub-navigation, but by doing that the user could dismiss the close button by scrolling down.

**Comment by AndyOGo** [comment]
BTW: why is the vertical gap so big between sub menu items?

**Comment by LucaMele** [comment]
I removed the sticky (which didnt behave as a sticky menu) and now is ok

**Comment by LucaMele** [comment]
closing as new plib version is live. If issue is with v2 still relevant, please re-open
